version: '3'
services:
  mysql-primary:
    image: mysql:8.0
    container_name: mysql-primary
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: ecdb
    volumes:
      - ecdb_mysql_data:/var/lib/mysql
      - ./mysql/primary/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - app-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p1234"]
      interval: 5s
      timeout: 3s
      retries: 20
  mysql-replica1:
    image: mysql:8.0
    container_name: mysql-replica1
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: ecdb
    depends_on:
      mysql-primary:
        condition: service_healthy
    volumes:
      - replica1_mysql_data:/var/lib/mysql
      - ./mysql/replica/my1.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - app-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p1234"]
      interval: 5s
      timeout: 3s
      retries: 20

  mysql-replica2:
    image: mysql:8.0
    container_name: mysql-replica2
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: ecdb
    depends_on:
      mysql-primary:
        condition: service_healthy
    volumes:
      - replica2_mysql_data:/var/lib/mysql
      - ./mysql/replica/my2.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - app-net
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-p1234" ]
      interval: 5s
      timeout: 3s
      retries: 20
  proxysql:
    image: proxysql/proxysql:3.0.7
    container_name: proxysql
    ports:
      - "6032:6032"
      - "6033:6033"
      - "6401:6401"
      - "6402:6402"
    volumes:
      - proxysql-data:/var/lib/proxysql
    networks:
      - app-net
    depends_on:
      mysql-primary:
        condition: service_healthy
      mysql-replica1:
        condition: service_healthy
      mysql-replica2:
        condition: service_healthy

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    networks:
      - app-net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
    networks:
      - app-net

  mysqld-exporter-primary:
    image: prom/mysqld-exporter:latest
    container_name: mysqld-exporter-primary
    command:
      - "--mysqld.address=mysql-primary:3306"
      - "--mysqld.username=exporter"
    environment:
      MYSQLD_EXPORTER_PASSWORD: 1234
    depends_on:
      mysql-primary:
        condition: service_healthy
    networks:
      - app-net

  mysqld-exporter-replica1:
    image: prom/mysqld-exporter:latest
    container_name: mysqld-exporter-replica1
    command:
      - "--mysqld.address=mysql-replica1:3306"
      - "--mysqld.username=exporter"
    environment:
      MYSQLD_EXPORTER_PASSWORD: 1234
    depends_on:
      mysql-replica1:
        condition: service_healthy
    networks:
      - app-net

  mysqld-exporter-replica2:
    image: prom/mysqld-exporter:latest
    container_name: mysqld-exporter-replica2
    command:
      - "--mysqld.address=mysql-replica2:3306"
      - "--mysqld.username=exporter"
    environment:
      MYSQLD_EXPORTER_PASSWORD: 1234
    depends_on:
      mysql-replica2:
        condition: service_healthy
    networks:
      - app-net

volumes:
  ecdb_mysql_data:
    external: true
  replica1_mysql_data:
  replica2_mysql_data:
  grafana-storage:
  prometheus-data:
  proxysql-data:

networks:
  app-net:
    driver: bridge

