package kr.hhplus.be.server.domain.common;

public enum ReservationReleaseReason {
	ORDER_CHANGED,
	PAYMENT_REPLACED,
	PAYMENT_EXPIRED,
	PAYMENT_FAILED,
	PAYMENT_CANCELED,
	ORDER_CANCELED,
	ADMIN_CANCELED,
	PAYMENT_REPREPARED
}
