spring:
  sql:
    init:
      mode: never

  jpa:
    show-sql: false # 부하테스트할 때는 꼭 꺼둬라.
    hibernate:
      format_sql: false
      highlight_sql: false
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true
    open-in-view: false

  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT:3306}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: primary-pool
      maximum-pool-size: ${DB_POOL_MAX:20}
      minimum-idle: ${DB_POOL_MIN:10}
      connection-timeout: ${HIKARI_CONNECTION_TIMEOUT}
      validation-timeout: 1000
      max-lifetime: ${HIKARI_MAX_LIFETIME}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}
      timeout: 500ms
      connect-timeout: 500ms
      database: 0

  redis:
    redisson:
      mode: file
      file: classpath:redisson.yml

app:
  redisson:
    enabled: true

logging:
  level:
    root: INFO
    org.hibernate.SQL: off #debug
    org.hibernate.orm.jdbc.bind: off #trace

server:
  tomcat:
    threads:
      max: 50
      min-spare: 50
    max-connections: 8192
    mbeanregistry:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  metrics:
    tags:
      application: ecommerce-app
    distribution:
      percentiles-histogram:
        coupon.redis.lua: true
      percentiles:
        coupon.redis.lua: 0.95,0.99
      minimum-expected-value:
        coupon.redis.lua: 1ms
      maximum-expected-value:
        coupon.redis.lua: 5s
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

