spring:
  sql:
    init:
      mode: always
  jpa:
    show-sql: false # 부하테스트할 때는 꼭 꺼둬라.
    hibernate:
      format_sql: false
      highlight_sql: false
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true
    open-in-view: false
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 500ms
      database: 0
  redis:
    redisson:
      mode: file
      file: classpath:redisson.yml

app:
  datasource:
    primary:
      url: jdbc:mysql://localhost:6401/ecdb
      username: appuser
      password: app1234
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        pool-name: primary-pool
        maximum-pool-size: 20
        minimum-idle: 10
        connection-timeout: 1000
        validation-timeout: 1000
        max-lifetime: 1800000
    replica:
      url: jdbc:mysql://localhost:6402/ecdb
      username: appuser
      password: app1234
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        pool-name: replica-pool
        maximum-pool-size: 10
        minimum-idle: 5
        connection-timeout: 1000
        validation-timeout: 1000
        max-lifetime: 1800000
  redisson:
    enabled: true
logging:
  level:
    org.hibernate.SQL: off #debug
    org.hibernate.orm.jdbc.bind: off #trace

server:
  tomcat:
    threads:
      max: 300
      min-spare: 50
    max-connections: 8192
    mbeanregistry:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  metrics:
    tags:
      application: ecommerce-app
    distribution:
      percentiles-histogram:
        coupon.redis.lua: true
      percentiles:
        coupon.redis.lua: 0.95,0.99
      minimum-expected-value:
        coupon.redis.lua: 1ms
      maximum-expected-value:
        coupon.redis.lua: 5s
  endpoint:
    health:
      show-details: always

