global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "spring-app"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["host.docker.internal:8080"]

  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "mysql-primary"
    static_configs:
      - targets: [ "mysqld-exporter-primary:9104" ]
        labels:
          role: "primary"

  - job_name: "mysql-replica1"
    static_configs:
      - targets: [ "mysqld-exporter-replica1:9104" ]
        labels:
          role: "replica"

  - job_name: "mysql-replica2"
    static_configs:
      - targets: [ "mysqld-exporter-replica2:9104" ]
        labels:
          role: "replica"

  - job_name: "redis"
    static_configs:
      - targets:
          - "redis-exporter:9121"